version: '3.8'

services:
  app:
    build: .
    container_name: app_container
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_PORT=${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
  
  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template:ro
    ports:
      - "80:80"
    depends_on:
      - app
    env_file: .env
    environment:
      - APP_PORT=${APP_PORT}
    command: >
      /bin/sh -c "envsubst '$$APP_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf
      && exec nginx -g 'daemon off;'"
